name: dumi book CI

# 只有在master分支发生push事件时触发
on:
  push:
    branches:
      - master

# 工作流
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # pull code
      - name: Checkout code
        uses: actions/checkout@v1

      # download Node
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      # build code
      - name: Build Project
        run: |
          npm install
          npm run build

      # deploy project
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: build
          folder: dist
          target-folder: fe-book




